/**
 * UUIDv7 (RFC 9562): 48-bit Unix timestamp in milliseconds, then random bits.
 * Generated by clients for messages, which makes sending idempotent and keeps
 * ids sortable by time (docs/04-architecture.md, section 4.3).
 */
export function uuidv7(timeMs: number, random: Uint8Array): string {
  if (random.length < 10) {
    throw new RangeError("uuidv7 needs at least 10 random bytes.");
  }
  if (!Number.isInteger(timeMs) || timeMs < 0 || timeMs >= 2 ** 48) {
    throw new RangeError("uuidv7 needs a 48-bit millisecond timestamp.");
  }
  const bytes = new Uint8Array(16);
  let time = timeMs;
  for (let i = 5; i >= 0; i--) {
    bytes[i] = time % 256;
    time = Math.floor(time / 256);
  }
  bytes.set(random.subarray(0, 10), 6);
  bytes[6] = 0x70 | ((bytes[6] ?? 0) & 0x0f); // version 7
  bytes[8] = 0x80 | ((bytes[8] ?? 0) & 0x3f); // RFC 9562 variant
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const UUIDV7_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export function isUuidv7(value: string): boolean {
  return UUIDV7_PATTERN.test(value);
}

/** Creation time encoded in a UUIDv7. */
export function uuidv7Time(id: string): number {
  return Number.parseInt(id.replaceAll("-", "").slice(0, 12), 16);
}
