/**
 * Checks on the UUIDv7 message ids generated by clients (`uuidv7` lives in
 * `ids/uuidv7.ts`): sending is idempotent and ids sort by time
 * (docs/04-architecture.md, section 4.3).
 */
const UUIDV7_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export function isUuidv7(value: string): boolean {
  return UUIDV7_PATTERN.test(value);
}

/** Creation time encoded in a UUIDv7. */
export function uuidv7Time(id: string): number {
  return Number.parseInt(id.replaceAll("-", "").slice(0, 12), 16);
}
