import { and, asc, count, desc, eq, gt, gte, inArray, isNull, lt, sql } from "drizzle-orm";
import type { Database } from "../client";
import { chatPreference, match, message, messageRead, notification, reaction } from "../schema";
import { enqueue } from "./outbox";

/** Message storage (CHAT-02). Bodies stay encrypted here; decryption happens in the API layer. */

export interface StoredMessage {
  readonly id: string;
  readonly matchId: string;
  readonly senderId: string | null;
  readonly kind: string;
  readonly bodyEncrypted: Uint8Array | null;
  readonly keyId: string | null;
  readonly replyTo: string | null;
  readonly createdAt: Date;
  readonly editedAt: Date | null;
  readonly deletedAt: Date | null;
  readonly moderation: unknown;
}

const messageColumns = {
  id: message.id,
  matchId: message.matchId,
  senderId: message.senderId,
  kind: message.kind,
  bodyEncrypted: message.bodyEncrypted,
  keyId: message.keyId,
  replyTo: message.replyTo,
  createdAt: message.createdAt,
  editedAt: message.editedAt,
  deletedAt: message.deletedAt,
  moderation: message.moderation,
};

/** The latest message of each match. */
export async function lastMessagesOf(
  db: Database,
  matchIds: readonly string[],
): Promise<Map<string, StoredMessage>> {
  if (matchIds.length === 0) {
    return new Map();
  }
  const rows = await db
    .selectDistinctOn([message.matchId], messageColumns)
    .from(message)
    .where(and(inArray(message.matchId, [...matchIds]), isNull(message.deletedAt)))
    .orderBy(message.matchId, desc(message.id));
  return new Map(rows.map((r) => [r.matchId, r]));
}

/**
 * A page of a conversation, oldest first. `before` loads older messages
 * (scrolling up), `after` catches up after a disconnection. Ids are UUIDv7:
 * ordering by id is ordering by time.
 */
export async function messagesOf(
  db: Database,
  matchId: string,
  options: { before?: string; after?: string; limit: number },
): Promise<{ messages: StoredMessage[]; hasMore: boolean }> {
  const conditions = [eq(message.matchId, matchId)];
  if (options.before) {
    conditions.push(lt(message.id, options.before));
  }
  if (options.after) {
    conditions.push(gt(message.id, options.after));
  }
  const rows = await db
    .select(messageColumns)
    .from(message)
    .where(and(...conditions))
    .orderBy(options.after ? asc(message.id) : desc(message.id))
    .limit(options.limit + 1);
  const hasMore = rows.length > options.limit;
  const page = rows.slice(0, options.limit);
  return { messages: options.after ? page : page.reverse(), hasMore };
}

export async function messagesByIds(db: Database, ids: readonly string[]): Promise<StoredMessage[]> {
  if (ids.length === 0) {
    return [];
  }
  return db
    .select(messageColumns)
    .from(message)
    .where(inArray(message.id, [...ids]));
}

export async function reactionsOf(db: Database, messageIds: readonly string[]) {
  if (messageIds.length === 0) {
    return [];
  }
  return db
    .select({ messageId: reaction.messageId, userId: reaction.userId, emoji: reaction.emoji })
    .from(reaction)
    .where(inArray(reaction.messageId, [...messageIds]));
}

/** Messages sent by a member since an instant (anti-spam quota). */
export async function messagesSentSince(db: Database, senderId: string, since: Date): Promise<number> {
  const [row] = await db
    .select({ value: count() })
    .from(message)
    .where(and(eq(message.senderId, senderId), gte(message.createdAt, since)));
  return row?.value ?? 0;
}

export interface NewMessage {
  readonly id: string;
  readonly matchId: string;
  /** Text by default; other kinds keep their JSON payload in the encrypted body. */
  readonly kind?: "text" | "sticker" | "gif" | "image" | "voice" | "date_proposal";
  /** Storage key of an attached file (photo, voice message). */
  readonly mediaKey?: string | null;
  readonly senderId: string;
  readonly recipientId: string;
  readonly body: { readonly keyId: string; readonly data: Uint8Array };
  readonly replyTo: string | null;
  readonly moderation: { readonly flags: readonly string[] } | null;
  readonly now: Date;
}

export type InsertMessageResult =
  | { readonly ok: true; readonly message: StoredMessage; readonly created: boolean }
  | { readonly ok: false; readonly reason: "id_conflict" | "invalid_reply" };

/**
 * Stores a message sent by a client. The id is generated by the client, so a
 * retry after a network loss returns the existing message instead of creating
 * a duplicate (docs/04-architecture.md, flow 4.3).
 */
export async function insertMessage(db: Database, input: NewMessage): Promise<InsertMessageResult> {
  return db.transaction(async (tx) => {
    const [existing] = await tx.select(messageColumns).from(message).where(eq(message.id, input.id));
    if (existing) {
      return existing.senderId === input.senderId && existing.matchId === input.matchId
        ? ({ ok: true, message: existing, created: false } as const)
        : ({ ok: false, reason: "id_conflict" } as const);
    }
    if (input.replyTo) {
      const [target] = await tx
        .select({ id: message.id })
        .from(message)
        .where(and(eq(message.id, input.replyTo), eq(message.matchId, input.matchId)));
      if (!target) {
        return { ok: false, reason: "invalid_reply" } as const;
      }
    }
    const [created] = await tx
      .insert(message)
      .values({
        id: input.id,
        matchId: input.matchId,
        senderId: input.senderId,
        kind: input.kind ?? "text",
        bodyEncrypted: input.body.data,
        mediaKey: input.mediaKey ?? null,
        keyId: input.body.keyId,
        replyTo: input.replyTo,
        moderation: input.moderation,
        createdAt: input.now,
      })
      .onConflictDoNothing()
      .returning(messageColumns);
    if (!created) {
      // A concurrent retry of the same message won the race.
      const [raced] = await tx.select(messageColumns).from(message).where(eq(message.id, input.id));
      return raced?.senderId === input.senderId
        ? ({ ok: true, message: raced, created: false } as const)
        : ({ ok: false, reason: "id_conflict" } as const);
    }
    await tx.update(match).set({ lastMessageAt: input.now }).where(eq(match.id, input.matchId));
    // The sender's read marker moves too: your own messages are never unread.
    await upsertRead(tx, input.matchId, input.senderId, input.id);
    // Grouping (NOT-06): one unread "new message" notification per conversation.
    await tx
      .delete(notification)
      .where(
        and(
          eq(notification.userId, input.recipientId),
          eq(notification.type, "message_received"),
          isNull(notification.readAt),
          sql`${notification.payload}->>'matchId' = ${input.matchId}`,
        ),
      );
    await tx
      .insert(notification)
      .values({ userId: input.recipientId, type: "message_received", payload: { matchId: input.matchId } });
    await enqueue(tx, [
      {
        userId: input.recipientId,
        event: { type: "message.created", matchId: input.matchId, messageId: input.id },
      },
      {
        userId: input.senderId,
        event: { type: "message.created", matchId: input.matchId, messageId: input.id },
      },
    ]);
    return { ok: true, message: created, created: true } as const;
  });
}

type Executor = Pick<Database, "insert">;

async function upsertRead(tx: Executor, matchId: string, userId: string, messageId: string) {
  await tx
    .insert(messageRead)
    .values({ matchId, userId, lastReadMessageId: messageId })
    .onConflictDoUpdate({
      target: [messageRead.matchId, messageRead.userId],
      set: { lastReadMessageId: messageId, updatedAt: new Date() },
      // Read markers only move forward.
      setWhere: sql`${messageRead.lastReadMessageId} < ${messageId}`,
    });
}

/** Moves the member's read marker forward. Returns true when it moved. */
export async function markRead(
  db: Database,
  matchId: string,
  userId: string,
  messageId: string,
): Promise<boolean> {
  return db.transaction(async (tx) => {
    const [target] = await tx
      .select({ id: message.id })
      .from(message)
      .where(and(eq(message.id, messageId), eq(message.matchId, matchId)));
    if (!target) {
      return false;
    }
    const [before] = await tx
      .select({ id: messageRead.lastReadMessageId })
      .from(messageRead)
      .where(and(eq(messageRead.matchId, matchId), eq(messageRead.userId, userId)));
    if (before && before.id >= messageId) {
      return false;
    }
    await upsertRead(tx, matchId, userId, messageId);
    await tx
      .update(notification)
      .set({ readAt: new Date() })
      .where(
        and(
          eq(notification.userId, userId),
          eq(notification.type, "message_received"),
          isNull(notification.readAt),
          sql`${notification.payload}->>'matchId' = ${matchId}`,
        ),
      );
    return true;
  });
}

export async function readMarkers(db: Database, matchId: string) {
  const rows = await db
    .select({ userId: messageRead.userId, lastReadMessageId: messageRead.lastReadMessageId })
    .from(messageRead)
    .where(eq(messageRead.matchId, matchId));
  return new Map(rows.map((r) => [r.userId, r.lastReadMessageId]));
}

/** Sets or removes the member's reaction on a message (one reaction per member and message). */
export async function setReaction(db: Database, messageId: string, userId: string, emoji: string | null) {
  if (emoji === null) {
    await db.delete(reaction).where(and(eq(reaction.messageId, messageId), eq(reaction.userId, userId)));
    return;
  }
  await db
    .insert(reaction)
    .values({ messageId, userId, emoji })
    .onConflictDoUpdate({
      target: [reaction.messageId, reaction.userId],
      set: { emoji, createdAt: new Date() },
    });
}

export interface ChatSettings {
  readonly readReceipts: boolean;
  readonly onlineStatus: boolean;
}

export const DEFAULT_CHAT_SETTINGS: ChatSettings = { readReceipts: true, onlineStatus: true };

export async function chatSettingsOf(
  db: Database,
  ids: readonly string[],
): Promise<Map<string, ChatSettings>> {
  const result = new Map<string, ChatSettings>(ids.map((id) => [id, DEFAULT_CHAT_SETTINGS]));
  if (ids.length === 0) {
    return result;
  }
  const rows = await db
    .select({
      userId: chatPreference.userId,
      readReceipts: chatPreference.readReceipts,
      onlineStatus: chatPreference.onlineStatus,
    })
    .from(chatPreference)
    .where(inArray(chatPreference.userId, [...ids]));
  for (const row of rows) {
    result.set(row.userId, { readReceipts: row.readReceipts, onlineStatus: row.onlineStatus });
  }
  return result;
}

export async function saveChatSettings(db: Database, userId: string, settings: ChatSettings) {
  await db
    .insert(chatPreference)
    .values({ userId, ...settings })
    .onConflictDoUpdate({ target: chatPreference.userId, set: { ...settings, updatedAt: new Date() } });
}

/** Lets the other member's open screens refresh a message (reaction, read marker…). */
export async function notifyMessageUpdated(
  db: Database,
  recipients: readonly string[],
  matchId: string,
  messageId: string,
) {
  await enqueue(
    db,
    recipients.map((userId) => ({ userId, event: { type: "message.updated" as const, matchId, messageId } })),
  );
}

export async function notifyRead(
  db: Database,
  recipientId: string,
  matchId: string,
  lastReadMessageId: string,
) {
  await enqueue(db, [{ userId: recipientId, event: { type: "message.read", matchId, lastReadMessageId } }]);
}

/**
 * Replaces the body of a text message (CHAT-08), only if it is still the
 * sender's, not deleted and within the window (checked again in SQL, so two
 * concurrent requests cannot race past it).
 */
export async function editMessageBody(
  db: Database,
  input: {
    id: string;
    senderId: string;
    body: { readonly keyId: string; readonly data: Uint8Array };
    moderation: { readonly flags: readonly string[] } | null;
    now: Date;
    windowMinutes: number;
  },
): Promise<StoredMessage | null> {
  const [row] = await db
    .update(message)
    .set({
      bodyEncrypted: input.body.data,
      keyId: input.body.keyId,
      moderation: input.moderation,
      editedAt: input.now,
    })
    .where(
      and(
        eq(message.id, input.id),
        eq(message.senderId, input.senderId),
        eq(message.kind, "text"),
        isNull(message.deletedAt),
        gt(message.createdAt, new Date(input.now.getTime() - input.windowMinutes * 60_000)),
      ),
    )
    .returning(messageColumns);
  return row ?? null;
}

/**
 * Deletes a message for everyone (CHAT-08). The body stays encrypted and
 * unreadable by both members for the moderation retention (a report can
 * still use it), then `purgeDeletedBodies` erases it. Reactions go at once.
 */
export async function deleteMessageForEveryone(
  db: Database,
  input: { id: string; senderId: string; now: Date; windowMinutes: number },
): Promise<StoredMessage | null> {
  return db.transaction(async (tx) => {
    const [row] = await tx
      .update(message)
      .set({ deletedAt: input.now })
      .where(
        and(
          eq(message.id, input.id),
          eq(message.senderId, input.senderId),
          isNull(message.deletedAt),
          gt(message.createdAt, new Date(input.now.getTime() - input.windowMinutes * 60_000)),
        ),
      )
      .returning(messageColumns);
    if (row) {
      await tx.delete(reaction).where(eq(reaction.messageId, input.id));
    }
    return row ?? null;
  });
}

/** Erases the bodies and media of messages deleted before `olderThan` (retention). */
export async function purgeDeletedBodies(db: Database, olderThan: Date): Promise<number> {
  const rows = await db
    .update(message)
    .set({ bodyEncrypted: null, keyId: null, mediaKey: null, moderation: null })
    .where(
      and(
        lt(message.deletedAt, olderThan),
        sql`(${message.bodyEncrypted} is not null or ${message.mediaKey} is not null)`,
      ),
    )
    .returning({ id: message.id });
  return rows.length;
}
