import { boolean, index, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { createdAt, timestamps } from "./columns";
import { appUser } from "./users";

/*
 * Better Auth tables (sessions, accounts, one-time codes, passkeys). Ids are
 * UUIDv7 generated by the application (`advanced.database.generateId`); the
 * user model is `app_user` (see users.ts).
 */

export const authSession = pgTable(
  "auth_session",
  {
    id: uuid().primaryKey(),
    userId: uuid()
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    token: text().notNull().unique(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    ipAddress: text(),
    userAgent: text(),
    /** Set when a staff member impersonates the user (admin plugin). */
    impersonatedBy: uuid(),
    ...timestamps,
  },
  (t) => [index().on(t.userId)],
);

export const authAccount = pgTable(
  "auth_account",
  {
    id: uuid().primaryKey(),
    userId: uuid()
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    accountId: text().notNull(),
    providerId: text().notNull(),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp({ withTimezone: true }),
    refreshTokenExpiresAt: timestamp({ withTimezone: true }),
    scope: text(),
    password: text(),
    ...timestamps,
  },
  (t) => [index().on(t.userId)],
);

/** One-time codes, stored hashed by the email OTP plugin. */
export const authVerification = pgTable(
  "auth_verification",
  {
    id: uuid().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    ...timestamps,
  },
  (t) => [index().on(t.identifier)],
);

export const authPasskey = pgTable(
  "auth_passkey",
  {
    id: uuid().primaryKey(),
    userId: uuid()
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    name: text(),
    publicKey: text().notNull(),
    credentialID: text("credential_id").notNull(),
    counter: integer().notNull(),
    deviceType: text().notNull(),
    backedUp: boolean().notNull(),
    transports: text(),
    aaguid: text(),
    createdAt: createdAt(),
  },
  (t) => [index().on(t.userId), index().on(t.credentialID)],
);
