import { type SQL, sql } from "drizzle-orm";
import { type AnyPgColumn, customType, timestamp, uuid } from "drizzle-orm/pg-core";

/** UUIDv7 primary key generated by PostgreSQL 18 (time-ordered, no guessable counter). */
export const id = () => uuid().primaryKey().default(sql`uuidv7()`);

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();

export const timestamps = {
  createdAt: createdAt(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

/** Raw bytes, for application-encrypted values (message bodies, report details). */
export const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType: () => "bytea",
});

// Values come from code constants, never from user input: inlining them is safe
// and keeps the generated DDL free of bind parameters.
const literals = (values: readonly string[]) =>
  sql.raw(values.map((value) => `'${value.replaceAll("'", "''")}'`).join(", "));

/** `CHECK (column IN (...))` for text columns used as enumerations. */
export function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  return sql`${column} in (${literals(values)})`;
}

/** `CHECK (column <@ ARRAY[...])` for text[] columns restricted to a set of values. */
export function subsetOf(column: AnyPgColumn, values: readonly string[]): SQL {
  return sql`${column} <@ array[${literals(values)}]::text[]`;
}
