import {
  boolean,
  check,
  index,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { bytea, createdAt, oneOf, timestamps } from "./columns";
import { match } from "./discovery";
import { appUser } from "./users";

export const MESSAGE_KINDS = ["text", "image", "voice", "gif", "sticker", "date_proposal", "system"] as const;

/**
 * A message. The id is a UUIDv7 generated by the client, which makes sending
 * idempotent (a retry after a network loss does not create a duplicate).
 * The body is encrypted by the application (docs/05-donnees.md, section 5).
 */
export const message = pgTable(
  "message",
  {
    id: uuid().primaryKey(),
    matchId: uuid()
      .notNull()
      .references(() => match.id, { onDelete: "cascade" }),
    /** Null for system messages and once the sender's account is deleted. */
    senderId: uuid().references(() => appUser.id, { onDelete: "set null" }),
    kind: text({ enum: MESSAGE_KINDS }).notNull(),
    bodyEncrypted: bytea(),
    keyId: text(),
    mediaKey: text(),
    replyTo: uuid(),
    moderation: jsonb(),
    createdAt: createdAt(),
    editedAt: timestamp({ withTimezone: true }),
    deletedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    check("message_kind_check", oneOf(t.kind, MESSAGE_KINDS)),
    index().on(t.matchId, t.id.desc()),
    index().on(t.senderId, t.createdAt),
  ],
);

export const messageRead = pgTable(
  "message_read",
  {
    matchId: uuid()
      .notNull()
      .references(() => match.id, { onDelete: "cascade" }),
    userId: uuid()
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    lastReadMessageId: uuid().notNull(),
    updatedAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.matchId, t.userId] })],
);

export const reaction = pgTable(
  "reaction",
  {
    messageId: uuid()
      .notNull()
      .references(() => message.id, { onDelete: "cascade" }),
    userId: uuid()
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    emoji: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.messageId, t.userId] })],
);

/**
 * Conversation settings (CHAT-02): read receipts and online status can be
 * turned off. Reciprocal: a member who hides them does not see others' either.
 */
export const chatPreference = pgTable("chat_preference", {
  userId: uuid()
    .primaryKey()
    .references(() => appUser.id, { onDelete: "cascade" }),
  readReceipts: boolean().notNull().default(true),
  onlineStatus: boolean().notNull().default(true),
  ...timestamps,
});

/**
 * Stored media waiting for deletion (CHAT-06, CHAT-07): a view-once photo a
 * few minutes after it was opened, the media of a message deleted for
 * everyone after the moderation retention. The worker empties it.
 */
export const mediaDeletion = pgTable("media_deletion", {
  storageKey: text().primaryKey(),
  deleteAfter: timestamp({ withTimezone: true }).notNull(),
});
