import { sql } from "drizzle-orm";
import type { Database } from "../client";
import { spot } from "../schema";

type SpotSeed = typeof spot.$inferInsert;

/**
 * Real public places of Lyon (IRL-02), around the Vaise campus and the
 * Presqu'île. Coordinates are approximate (a few dozen metres) and must be
 * checked on site before launch; descriptions stay factual.
 */
export const SPOTS: readonly Omit<SpotSeed, "id" | "position">[] = [
  {
    slug: "place-valmy",
    nameFr: "Place Valmy",
    nameEn: "Place Valmy",
    kind: "square",
    area: "vaise",
    latitude: 45.7744,
    longitude: 4.8054,
    descriptionFr: "Le cœur de Vaise, à deux pas du campus et du métro D.",
    descriptionEn: "The heart of Vaise, a short walk from the campus and metro line D.",
  },
  {
    slug: "berges-de-saone-vaise",
    nameFr: "Berges de la Saône (quai Paul-Sédallian)",
    nameEn: "Saône riverbanks (quai Paul-Sédallian)",
    kind: "riverbank",
    area: "vaise",
    latitude: 45.7812,
    longitude: 4.8108,
    descriptionFr: "Une balade au bord de l'eau, au calme, côté Vaise.",
    descriptionEn: "A quiet walk along the water, on the Vaise side.",
  },
  {
    slug: "ile-barbe",
    nameFr: "Île Barbe",
    nameEn: "Île Barbe",
    kind: "park",
    area: "nord",
    latitude: 45.7972,
    longitude: 4.8328,
    descriptionFr: "Une petite île sur la Saône, avec un jardin ouvert au public.",
    descriptionEn: "A small island on the Saône, with a garden open to the public.",
  },
  {
    slug: "parc-du-vallon",
    nameFr: "Parc du Vallon",
    nameEn: "Parc du Vallon",
    kind: "park",
    area: "nord",
    latitude: 45.7862,
    longitude: 4.7958,
    descriptionFr: "Un grand parc à la Duchère, avec un étang et des pelouses.",
    descriptionEn: "A large park in La Duchère, with a pond and lawns.",
  },
  {
    slug: "place-des-terreaux",
    nameFr: "Place des Terreaux",
    nameEn: "Place des Terreaux",
    kind: "square",
    area: "presquile",
    latitude: 45.7675,
    longitude: 4.8336,
    descriptionFr: "La place de l'hôtel de ville et de sa grande fontaine.",
    descriptionEn: "The town hall square, with its large fountain.",
  },
  {
    slug: "place-sathonay",
    nameFr: "Place Sathonay",
    nameEn: "Place Sathonay",
    kind: "square",
    area: "presquile",
    latitude: 45.7699,
    longitude: 4.8285,
    descriptionFr: "Une place ombragée au pied des pentes de la Croix-Rousse.",
    descriptionEn: "A shaded square at the foot of the Croix-Rousse slopes.",
  },
  {
    slug: "jardin-des-chartreux",
    nameFr: "Jardin des Chartreux",
    nameEn: "Jardin des Chartreux",
    kind: "viewpoint",
    area: "presquile",
    latitude: 45.7714,
    longitude: 4.8247,
    descriptionFr: "Un jardin en terrasse avec vue sur la Saône et Fourvière.",
    descriptionEn: "A terraced garden overlooking the Saône and Fourvière.",
  },
  {
    slug: "place-des-jacobins",
    nameFr: "Place des Jacobins",
    nameEn: "Place des Jacobins",
    kind: "square",
    area: "presquile",
    latitude: 45.7609,
    longitude: 4.8335,
    descriptionFr: "Une place centrale de la Presqu'île, autour de sa fontaine.",
    descriptionEn: "A central square of the Presqu'île, around its fountain.",
  },
  {
    slug: "place-bellecour",
    nameFr: "Place Bellecour",
    nameEn: "Place Bellecour",
    kind: "square",
    area: "presquile",
    latitude: 45.7578,
    longitude: 4.832,
    descriptionFr: "La grande place piétonne au centre de Lyon, facile à trouver.",
    descriptionEn: "The large pedestrian square in the centre of Lyon, easy to find.",
  },
  {
    slug: "place-antonin-poncet",
    nameFr: "Place Antonin-Poncet",
    nameEn: "Place Antonin-Poncet",
    kind: "square",
    area: "presquile",
    latitude: 45.7564,
    longitude: 4.8352,
    descriptionFr: "Une place ouverte sur le Rhône, juste à côté de Bellecour.",
    descriptionEn: "A square opening onto the Rhône, right next to Bellecour.",
  },
  {
    slug: "place-carnot",
    nameFr: "Place Carnot",
    nameEn: "Place Carnot",
    kind: "square",
    area: "presquile",
    latitude: 45.7497,
    longitude: 4.8263,
    descriptionFr: "Une place arborée près de la gare de Perrache.",
    descriptionEn: "A tree-lined square near Perrache station.",
  },
  {
    slug: "place-saint-jean",
    nameFr: "Place Saint-Jean",
    nameEn: "Place Saint-Jean",
    kind: "square",
    area: "vieux-lyon",
    latitude: 45.761,
    longitude: 4.8274,
    descriptionFr: "Le parvis de la cathédrale, au cœur du Vieux-Lyon.",
    descriptionEn: "The cathedral square, in the heart of Vieux-Lyon.",
  },
  {
    slug: "jardin-du-rosaire",
    nameFr: "Jardin du Rosaire",
    nameEn: "Jardin du Rosaire",
    kind: "viewpoint",
    area: "vieux-lyon",
    latitude: 45.7616,
    longitude: 4.8247,
    descriptionFr: "Un jardin en pente sur la colline de Fourvière, avec vue sur la ville.",
    descriptionEn: "A sloping garden on Fourvière hill, with a view over the city.",
  },
  {
    slug: "berges-du-rhone",
    nameFr: "Berges du Rhône",
    nameEn: "Rhône riverbanks",
    kind: "riverbank",
    area: "rive-gauche",
    latitude: 45.759,
    longitude: 4.8425,
    descriptionFr: "Les quais aménagés de la rive gauche, à pied ou à vélo.",
    descriptionEn: "The landscaped left-bank quays, on foot or by bike.",
  },
  {
    slug: "parc-de-la-tete-d-or",
    nameFr: "Parc de la Tête d'Or",
    nameEn: "Parc de la Tête d'Or",
    kind: "park",
    area: "rive-gauche",
    latitude: 45.7772,
    longitude: 4.8556,
    descriptionFr: "Le grand parc de Lyon, avec son lac et ses grandes allées.",
    descriptionEn: "Lyon's big park, with its lake and wide paths.",
  },
  {
    slug: "place-nautique",
    nameFr: "Place nautique",
    nameEn: "Place nautique",
    kind: "riverbank",
    area: "confluence",
    latitude: 45.7428,
    longitude: 4.818,
    descriptionFr: "Le bassin de la Confluence et ses pontons, au bord de la Saône.",
    descriptionEn: "The Confluence basin and its pontoons, by the Saône.",
  },
];

/** Idempotent: upsert by slug, in list order. */
export async function seedSpots(db: Database) {
  await db
    .insert(spot)
    .values(SPOTS.map((s, position) => ({ ...s, position })))
    .onConflictDoUpdate({
      target: spot.slug,
      set: {
        nameFr: sql`excluded.name_fr`,
        nameEn: sql`excluded.name_en`,
        kind: sql`excluded.kind`,
        area: sql`excluded.area`,
        latitude: sql`excluded.latitude`,
        longitude: sql`excluded.longitude`,
        descriptionFr: sql`excluded.description_fr`,
        descriptionEn: sql`excluded.description_en`,
        position: sql`excluded.position`,
      },
    });
}
